import { useState } from "react";

const SPORTS = ["Boxing", "Wrestling", "Judo", "Swimming", "MMA", "Taekwondo", "Kickboxing"];
const COUNTRIES = ["Samoa", "American Samoa", "Tonga", "Fiji", "Cook Islands", "Vanuatu", "Niue", "Tokelau", "New Zealand", "Australia"];
const PASSPORT_TYPES = ["Samoan", "Tongan", "Fijian", "Cook Islands", "New Zealand", "Australian", "Other"];

const DOC_TYPES = [
  { id: "visa_letter", icon: "📋", title: "Visa Support Letter", desc: "Official letter for embassy applications listing team members and travel purpose" },
  { id: "team_roster", icon: "👥", title: "Team Roster", desc: "Formatted athlete list with passport details, weight categories and DOB" },
  { id: "funding_request", icon: "💰", title: "Ministry Funding Request", desc: "Budget breakdown letter in the format Sports Ministries require" },
  { id: "entry_form", icon: "🥊", title: "Tournament Entry Form", desc: "Pre-filled entry form ready to send to tournament organisers" },
];function printDocument(html, title) {
  const win = window.open("", "_blank");
  win.document.write(`<!DOCTYPE html><html><head><title>${title}</title><style>* { margin: 0; padding: 0; box-sizing: border-box; } body { font-family: 'Georgia', serif; font-size: 12pt; color: #1a1a1a; padding: 40px; max-width: 800px; margin: 0 auto; } .header { border-bottom: 3px solid #1a1a1a; padding-bottom: 16px; margin-bottom: 24px; display: flex; justify-content: space-between; align-items: flex-end; } .org-name { font-size: 18pt; font-weight: bold; letter-spacing: 1px; } .doc-type { font-size: 9pt; text-transform: uppercase; letter-spacing: 2px; color: #555; } .date-ref { text-align: right; font-size: 10pt; color: #444; } h1 { font-size: 14pt; text-transform: uppercase; letter-spacing: 1px; margin: 24px 0 8px; border-bottom: 1px solid #ccc; padding-bottom: 4px; } p { line-height: 1.7; margin-bottom: 10px; } table { width: 100%; border-collapse: collapse; margin: 12px 0; font-size: 10pt; } th { background: #1a1a1a; color: white; padding: 8px 10px; text-align: left; font-size: 9pt; text-transform: uppercase; } td { padding: 7px 10px; border-bottom: 1px solid #e0e0e0; } tr:nth-child(even) td { background: #f9f9f9; } .signature-block { margin-top: 40px; } .sig-line { border-top: 1px solid #1a1a1a; width: 220px; margin-top: 40px; padding-top: 4px; font-size: 10pt; } .footer { margin-top: 40px; padding-top: 12px; border-top: 1px solid #ccc; font-size: 9pt; color: #666; text-align: center; } .highlight-box { background: #f5f5f5; border-left: 4px solid #C9A84C; padding: 12px 16px; margin: 16px 0; } @media print { body { padding: 20px; } }</style></head><body>${html}</body></html>`);
  win.document.close();
  setTimeout(() => { win.print(); }, 500);
}

function generateVisaLetter(data) {
  const athletes = data.athletes.map((a, i) => `<tr><td>${i + 1}</td><td>${a.name}</td><td>${a.passport}</td><td>${a.dob}</td><td>${a.category}</td></tr>`).join("");
  const html = `<div class="header"><div><div class="org-name">${data.orgName}</div><div class="doc-type">Official Visa Support Letter</div></div><div class="date-ref"><div>Ref: ${data.orgName.replace(/\s/g,"").toUpperCase().slice(0,4)}-${new Date().getFullYear()}-001</div><div>${new Date().toLocaleDateString("en-NZ",{day:"numeric",month:"long",year:"numeric"})}</div></div></div><p>To Whom It May Concern,</p><p>The <strong>${data.orgName}</strong> hereby confirms and supports the visa application for the following delegation travelling to compete in the <strong>${data.tournament}</strong> to be held in <strong>${data.country}</strong> from <strong>${data.startDate}</strong> to <strong>${data.endDate}</strong>.</p><h1>Delegation Details</h1><div class="highlight-box"><p><strong>Sport:</strong> ${data.sport}</p><p><strong>Tournament:</strong> ${data.tournament}</p><p><strong>Host Country:</strong> ${data.country}</p><p><strong>Travel Dates:</strong> ${data.startDate} — ${data.endDate}</p><p><strong>Number of Athletes:</strong> ${data.athletes.length}</p><p><strong>Number of Officials:</strong> ${data.officials}</p></div><h1>Athletes Travelling</h1><table><tr><th>#</th><th>Full Name</th><th>Passport No.</th><th>Date of Birth</th><th>Category</th></tr>${athletes}</table><h1>Purpose of Travel</h1><p>This delegation is travelling solely for the purpose of representing ${data.homeCountry} in international ${data.sport} competition. All team members hold valid passports and will return to ${data.homeCountry} immediately upon conclusion of the tournament.</p><p>The ${data.orgName} takes full responsibility for ensuring all delegates comply with the visa conditions and return travel requirements of the host country.</p><div class="signature-block"><p>Yours faithfully,</p><div class="sig-line">${data.headCoach}<br><em>Head Coach / Team Manager</em></div></div><div class="footer">Generated by SportsTripz — sportstripz.vercel.app</div>`;
  printDocument(html, "Visa Support Letter");
}

function generateTeamRoster(data) {
  const athletes = data.athletes.map((a, i) => `<tr><td>${i + 1}</td><td>${a.name}</td><td>${a.dob}</td><td>${a.passport}</td><td>${a.passportExpiry}</td><td>${a.category}</td><td>${a.weight}</td></tr>`).join("");
  const html = `<div class="header"><div><div class="org-name">${data.orgName}</div><div class="doc-type">Official Team Roster — ${data.sport}</div></div><div class="date-ref"><div>${new Date().toLocaleDateString("en-NZ",{day:"numeric",month:"long",year:"numeric"})}</div></div></div><div class="highlight-box"><p><strong>Tournament:</strong> ${data.tournament}</p><p><strong>Location:</strong> ${data.country}</p><p><strong>Dates:</strong> ${data.startDate} — ${data.endDate}</p><p><strong>Head Coach:</strong> ${data.headCoach}</p></div><h1>Athletes</h1><table><tr><th>#</th><th>Full Name</th><th>Date of Birth</th><th>Passport No.</th><th>Passport Expiry</th><th>Category</th><th>Weight (kg)</th></tr>${athletes}</table><h1>Officials</h1><table><tr><th>Role</th><th>Full Name</th><th>Passport No.</th></tr><tr><td>Head Coach</td><td>${data.headCoach}</td><td>${data.coachPassport||"—"}</td></tr></table><div class="signature-block"><p>I certify that the above information is correct and all athletes are eligible to compete.</p><div class="sig-line">${data.headCoach}<br><em>Head Coach / Team Manager</em></div></div><div class="footer">Generated by SportsTripz — sportstripz.vercel.app</div>`;
  printDocument(html, "Team Roster");
}

function generateFundingRequest(data) {
  const totalAthletes = data.athletes.length;
  const flightCost = parseFloat(data.flightCostPerPerson||0) * (totalAthletes + parseInt(data.officials||1));
  const entryCost = parseFloat(data.entryFeePerAthlete||0) * totalAthletes;
  const accomCost = parseFloat(data.accomPerNight||0) * parseInt(data.nights||1) * (totalAthletes + parseInt(data.officials||1));
  const perDiem = parseFloat(data.perDiemPerDay||0) * parseInt(data.nights||1) * (totalAthletes + parseInt(data.officials||1));
  const visaCost = parseFloat(data.visaCostPerPerson||0) * (totalAthletes + parseInt(data.officials||1));
  const total = flightCost + entryCost + accomCost + perDiem + visaCost + parseFloat(data.otherCosts||0);
  const html = `<div class="header"><div><div class="org-name">${data.orgName}</div><div class="doc-type">Sports Ministry Funding Application</div></div><div class="date-ref"><div>${new Date().toLocaleDateString("en-NZ",{day:"numeric",month:"long",year:"numeric"})}</div></div></div><p>To the Minister of Sport,</p><p>The <strong>${data.orgName}</strong> respectfully requests financial support to send our national ${data.sport} team to compete in the <strong>${data.tournament}</strong> in <strong>${data.country}</strong>.</p><h1>Event Details</h1><div class="highlight-box"><p><strong>Event:</strong> ${data.tournament}</p><p><strong>Host Country:</strong> ${data.country}</p><p><strong>Dates:</strong> ${data.startDate} — ${data.endDate}</p><p><strong>Athletes:</strong> ${totalAthletes} | <strong>Officials:</strong> ${data.officials}</p></div><h1>Budget Breakdown</h1><table><tr><th>Item</th><th>Unit Cost</th><th>Qty</th><th>Total</th></tr><tr><td>Flights (return)</td><td>$${Number(data.flightCostPerPerson).toLocaleString()}</td><td>${totalAthletes+parseInt(data.officials||1)}</td><td>$${flightCost.toLocaleString()}</td></tr><tr><td>Entry Fees</td><td>$${Number(data.entryFeePerAthlete).toLocaleString()}</td><td>${totalAthletes}</td><td>$${entryCost.toLocaleString()}</td></tr><tr><td>Accommodation</td><td>$${Number(data.accomPerNight).toLocaleString()}/night</td><td>${totalAthletes+parseInt(data.officials||1)} x ${data.nights} nights</td><td>$${accomCost.toLocaleString()}</td></tr><tr><td>Per Diem</td><td>$${Number(data.perDiemPerDay).toLocaleString()}/day</td><td>${totalAthletes+parseInt(data.officials||1)} x ${data.nights} days</td><td>$${perDiem.toLocaleString()}</td></tr><tr><td>Visa Fees</td><td>$${Number(data.visaCostPerPerson).toLocaleString()}</td><td>${totalAthletes+parseInt(data.officials||1)}</td><td>$${visaCost.toLocaleString()}</td></tr><tr><th colspan="3">TOTAL REQUESTED</th><th>$${total.toLocaleString()}</th></tr></table><p>${data.significance||"Participation in this event represents a critical development opportunity for our athletes."}</p><p>We respectfully request your support of <strong>$${total.toLocaleString()}</strong>.</p><div class="signature-block"><div class="sig-line">${data.headCoach}<br><em>Head Coach, ${data.orgName}</em></div></div><div class="footer">Generated by SportsTripz — sportstripz.vercel.app</div>`;
  printDocument(html, "Ministry Funding Request");
}

function generateEntryForm(data) {
  const athletes = data.athletes.map((a, i) => `<tr><td>${i + 1}</td><td>${a.name}</td><td>${a.dob}</td><td>${a.category}</td><td>${a.weight}</td><td>${data.homeCountry}</td></tr>`).join("");
  const html = `<div class="header"><div><div class="org-name">${data.tournament}</div><div class="doc-type">Official Entry Form — ${data.sport}</div></div><div class="date-ref"><div>Submitted: ${new Date().toLocaleDateString("en-NZ",{day:"numeric",month:"long",year:"numeric"})}</div></div></div><h1>Entering Organisation</h1><div class="highlight-box"><p><strong>Organisation:</strong> ${data.orgName}</p><p><strong>Country:</strong> ${data.homeCountry}</p><p><strong>Head Coach:</strong> ${data.headCoach}</p><p><strong>Email:</strong> ${data.email||"—"}</p><p><strong>Phone:</strong> ${data.phone||"—"}</p></div><h1>Athletes Entered</h1><table><tr><th>#</th><th>Full Name</th><th>Date of Birth</th><th>Category</th><th>Weight (kg)</th><th>Country</th></tr>${athletes}</table><div class="signature-block"><p>I confirm all athletes listed are eligible to compete and represent ${data.homeCountry}.</p><div class="sig-line">${data.headCoach}<br><em>Head Coach, ${data.orgName}</em></div></div><div class="footer">Generated by SportsTripz — sportstripz.vercel.app</div>`;
  printDocument(html, "Tournament Entry Form");
}Great! Now paste **Part 3** — click at the very end of the text in Notepad and paste this:

---

```
function Label({ children }) {
  return <div style={{ color: "#aaa", fontSize: 12, marginBottom: 4, textTransform: "uppercase", letterSpacing: 1 }}>{children}</div>;
}

function Row({ label, required, children }) {
  return <div><Label>{label}{required && " *"}</Label>{children}</div>;
}

function Input({ value, onChange, placeholder, type = "text" }) {
  return <input type={type} value={value || ""} onChange={e => onChange(e.target.value)} placeholder={placeholder} style={{ width: "100%", background: "#1a1a1a", border: "1px solid #333", borderRadius: 6, color: "#fff", padding: "10px 12px", fontSize: 14 }} />;
}

function Select({ value, onChange, options }) {
  return <select value={value || ""} onChange={e => onChange(e.target.value)} style={{ width: "100%", background: "#1a1a1a", border: "1px solid #333", borderRadius: 6, color: "#fff", padding: "10px 12px", fontSize: 14 }}><option value="">Select...</option>{options.map(o => <option key={o} value={o}>{o}</option>)}</select>;
}

function StepOrgInfo({ data, onChange }) {
  return (
    <div style={{ display: "flex", flexDirection: "column", gap: 16 }}>
      <h3 style={{ color: "#C9A84C", fontSize: 14, textTransform: "uppercase", letterSpacing: 2 }}>Organisation Details</h3>
      <Row label="Organisation Name" required><Input value={data.orgName} onChange={v => onChange("orgName", v)} placeholder="Samoa United Boxing Association" /></Row>
      <Row label="Home Country"><Select value={data.homeCountry} onChange={v => onChange("homeCountry", v)} options={COUNTRIES} /></Row>
      <Row label="Sport"><Select value={data.sport} onChange={v => onChange("sport", v)} options={SPORTS} /></Row>
      <Row label="Head Coach / Team Manager" required><Input value={data.headCoach} onChange={v => onChange("headCoach", v)} placeholder="Full name" /></Row>
      <Row label="Coach Passport No."><Input value={data.coachPassport} onChange={v => onChange("coachPassport", v)} placeholder="A1234567" /></Row>
      <Row label="Contact Email"><Input value={data.email} onChange={v => onChange("email", v)} placeholder="coach@example.com" type="email" /></Row>
      <Row label="Contact Phone"><Input value={data.phone} onChange={v => onChange("phone", v)} placeholder="+685 123 4567" /></Row>
    </div>
  );
}

function StepTournament({ data, onChange }) {
  return (
    <div style={{ display: "flex", flexDirection: "column", gap: 16 }}>
      <h3 style={{ color: "#C9A84C", fontSize: 14, textTransform: "uppercase", letterSpacing: 2 }}>Tournament Details</h3>
      <Row label="Tournament Name" required><Input value={data.tournament} onChange={v => onChange("tournament", v)} placeholder="Bosnia Open 2025" /></Row>
      <Row label="Host Country" required><Input value={data.country} onChange={v => onChange("country", v)} placeholder="Bosnia & Herzegovina" /></Row>
      <Row label="Start Date" required><Input value={data.startDate} onChange={v => onChange("startDate", v)} type="date" /></Row>
      <Row label="End Date" required><Input value={data.endDate} onChange={v => onChange("endDate", v)} type="date" /></Row>
      <Row label="Number of Nights"><Input value={data.nights} onChange={v => onChange("nights", v)} type="number" placeholder="7" /></Row>
      <Row label="Number of Officials (incl. coach)"><Input value={data.officials} onChange={v => onChange("officials", v)} type="number" placeholder="2" /></Row>
    </div>
  );
}

function StepAthletes({ data, onChange }) {
  const athletes = data.athletes || [{ name: "", dob: "", passport: "", passportExpiry: "", passportType: "Samoan", category: "", weight: "" }];
  function updateAthlete(idx, field, val) {
    onChange("athletes", athletes.map((a, i) => i === idx ? { ...a, [field]: val } : a));
  }
  function addAthlete() {
    onChange("athletes", [...athletes, { name: "", dob: "", passport: "", passportExpiry: "", passportType: "Samoan", category: "", weight: "" }]);
  }
  function removeAthlete(idx) {
    onChange("athletes", athletes.filter((_, i) => i !== idx));
  }
  return (
    <div style={{ display: "flex", flexDirection: "column", gap: 20 }}>
      <h3 style={{ color: "#C9A84C", fontSize: 14, textTransform: "uppercase", letterSpacing: 2 }}>Athletes</h3>
      {athletes.map((a, idx) => (
        <div key={idx} style={{ background: "#1a1a1a", border: "1px solid #333", borderRadius: 8, padding: 16 }}>
          <div style={{ display: "flex", justifyContent: "space-between", marginBottom: 12 }}>
            <span style={{ color: "#C9A84C", fontWeight: 700 }}>Athlete {idx + 1}</span>
            {athletes.length > 1 && <button onClick={() => removeAthlete(idx)} style={{ background: "none", border: "1px solid #555", color: "#aaa", borderRadius: 4, padding: "2px 10px", cursor: "pointer", fontSize: 12 }}>Remove</button>}
          </div>
          <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 10 }}>
            <div style={{ gridColumn: "1/-1" }}><Label>Full Name *</Label><Input value={a.name} onChange={v => updateAthlete(idx, "name", v)} placeholder="Full legal name" /></div>
            <div><Label>Date of Birth</Label><Input value={a.dob} onChange={v => updateAthlete(idx, "dob", v)} type="date" /></div>
            <div><Label>Passport No.</Label><Input value={a.passport} onChange={v => updateAthlete(idx, "passport", v)} placeholder="A1234567" /></div>
            <div><Label>Passport Expiry</Label><Input value={a.passportExpiry} onChange={v => updateAthlete(idx, "passportExpiry", v)} type="date" /></div>
            <div><Label>Passport Type</Label><Select value={a.passportType} onChange={v => updateAthlete(idx, "passportType", v)} options={PASSPORT_TYPES} /></div>
            <div><Label>Weight Category</Label><Input value={a.category} onChange={v => updateAthlete(idx, "category", v)} placeholder="e.g. 67kg, Junior" /></div>
            <div><Label>Body Weight (kg)</Label><Input value={a.weight} onChange={v => updateAthlete(idx, "weight", v)} type="number" /></div>
          </div>
        </div>
      ))}
      <button onClick={addAthlete} style={{ background: "none", border: "2px dashed #C9A84C", color: "#C9A84C", borderRadius: 8, padding: 12, cursor: "pointer", fontSize: 14, fontWeight: 700 }}>+ Add Another Athlete</button>
    </div>
  );
}

function StepBudget({ data, onChange }) {
  return (
    <div style={{ display: "flex", flexDirection: "column", gap: 16 }}>
      <h3 style={{ color: "#C9A84C", fontSize: 14, textTransform: "uppercase", letterSpacing: 2 }}>Budget</h3>
      <Row label="Flight Cost per Person (return)"><Input value={data.flightCostPerPerson} onChange={v => onChange("flightCostPerPerson", v)} type="number" placeholder="2500" /></Row>
      <Row label="Entry Fee per Athlete"><Input value={data.entryFeePerAthlete} onChange={v => onChange("entryFeePerAthlete", v)} type="number" placeholder="200" /></Row>
      <Row label="Accommodation per Person per Night"><Input value={data.accomPerNight} onChange={v => onChange("accomPerNight", v)} type="number" placeholder="80" /></Row>
      <Row label="Per Diem per Person per Day"><Input value={data.perDiemPerDay} onChange={v => onChange("perDiemPerDay", v)} type="number" placeholder="50" /></Row>
      <Row label="Visa Fee per Person"><Input value={data.visaCostPerPerson} onChange={v => onChange("visaCostPerPerson", v)} type="number" placeholder="120" /></Row>
      <Row label="Other Costs (total)"><Input value={data.otherCosts} onChange={v => onChange("otherCosts", v)} type="number" placeholder="300" /></Row>
      <Row label="Why this trip matters (optional)"><textarea value={data.significance} onChange={e => onChange("significance", e.target.value)} placeholder="Describe the significance..." style={{ width: "100%", background: "#1a1a1a", border: "1px solid #333", borderRadius: 6, color: "#fff", padding: "10px 12px", fontSize: 14, minHeight: 80, resize: "vertical" }} /></Row>
    </div>
  );
}

export default function DocumentGenerator() {
  const [selectedDoc, setSelectedDoc] = useState(null);
  const [step, setStep] = useState(0);
  const [formData, setFormData] = useState({
    orgName: "", homeCountry: "Samoa", sport: "Boxing", headCoach: "", coachPassport: "",
    email: "", phone: "", tournament: "", country: "", startDate: "", endDate: "",
    nights: "", officials: "2", athletes: [{ name: "", dob: "", passport: "", passportExpiry: "", passportType: "Samoan", category: "", weight: "" }],
    flightCostPerPerson: "", entryFeePerAthlete: "", accomPerNight: "", perDiemPerDay: "", visaCostPerPerson: "", otherCosts: "", significance: "",
  });

  function update(key, val) { setFormData(prev => ({ ...prev, [key]: val })); }

  const needsBudget = selectedDoc === "funding_request";
  const steps = [
    { label: "Organisation", component: <StepOrgInfo data={formData} onChange={update} /> },
    { label: "Tournament", component: <StepTournament data={formData} onChange={update} /> },
    { label: "Athletes", component: <StepAthletes data={formData} onChange={update} /> },
    ...(needsBudget ? [{ label: "Budget", component: <StepBudget data={formData} onChange={update} /> }] : []),
  ];

  function generate() {
    if (selectedDoc === "visa_letter") generateVisaLetter(formData);
    else if (selectedDoc === "team_roster") generateTeamRoster(formData);
    else if (selectedDoc === "funding_request") generateFundingRequest(formData);
    else if (selectedDoc === "entry_form") generateEntryForm(formData);
  }

  if (!selectedDoc) {
    return (
      <div style={{ padding: "40px 24px", maxWidth: 860, margin: "0 auto" }}>
        <h2 style={{ fontFamily: "'Bebas Neue', sans-serif", fontSize: 36, color: "#fff", letterSpacing: 2, marginBottom: 8 }}>Document <span style={{ color: "#C9A84C" }}>Generator</span></h2>
        <p style={{ color: "#aaa", marginBottom: 32 }}>Generate official documents for visa applications, tournament entry, and government funding.</p>
        <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 16 }}>
          {DOC_TYPES.map(doc => (
            <button key={doc.id} onClick={() => { setSelectedDoc(doc.id); setStep(0); }} style={{ background: "#111", border: "1px solid #333", borderRadius: 10, padding: "24px 20px", textAlign: "left", cursor: "pointer" }} onMouseEnter={e => e.currentTarget.style.borderColor = "#C9A84C"} onMouseLeave={e => e.currentTarget.style.borderColor = "#333"}>
              <div style={{ fontSize: 32, marginBottom: 10 }}>{doc.icon}</div>
              <div style={{ color: "#fff", fontWeight: 700, fontSize: 15, marginBottom: 6 }}>{doc.title}</div>
              <div style={{ color: "#aaa", fontSize: 13, lineHeight: 1.5 }}>{doc.desc}</div>
            </button>
          ))}
        </div>
      </div>
    );
  }

  const currentDoc = DOC_TYPES.find(d => d.id === selectedDoc);
  return (
    <div style={{ padding: "40px 24px", maxWidth: 700, margin: "0 auto" }}>
      <div style={{ display: "flex", alignItems: "center", gap: 12, marginBottom: 8 }}>
        <button onClick={() => setSelectedDoc(null)} style={{ background: "none", border: "none", color: "#C9A84C", cursor: "pointer", fontSize: 22 }}>←</button>
        <h2 style={{ fontFamily: "'Bebas Neue', sans-serif", fontSize: 28, color: "#fff", letterSpacing: 2 }}>{currentDoc.icon} {currentDoc.title}</h2>
      </div>
      <div style={{ display: "flex", gap: 8, marginBottom: 32 }}>
        {steps.map((s, i) => (
          <div key={i} style={{ flex: 1, textAlign: "center" }}>
            <div style={{ height: 4, borderRadius: 2, background: i <= step ? "#C9A84C" : "#333", marginBottom: 6 }} />
            <div style={{ fontSize: 11, color: i <= step ? "#C9A84C" : "#555", textTransform: "uppercase", letterSpacing: 1 }}>{s.label}</div>
          </div>
        ))}
      </div>
      <div style={{ marginBottom: 32 }}>{steps[step]?.component}</div>
      <div style={{ display: "flex", gap: 12, justifyContent: "space-between" }}>
        <button onClick={() => step > 0 ? setStep(step - 1) : setSelectedDoc(null)} style={{ background: "none", border: "1px solid #444", color: "#aaa", borderRadius: 8, padding: "12px 24px", cursor: "pointer", fontSize: 14 }}>{step === 0 ? "← Back" : "Previous"}</button>
        {step < steps.length - 1
          ? <button onClick={() => setStep(step + 1)} style={{ background: "#C9A84C", border: "none", color: "#000", borderRadius: 8, padding: "12px 32px", cursor: "pointer", fontSize: 14, fontWeight: 700 }}>Next →</button>
          : <button onClick={generate} style={{ background: "#C9A84C", border: "none", color: "#000", borderRadius: 8, padding: "12px 32px", cursor: "pointer", fontSize: 14, fontWeight: 700 }}>📄 Generate & Print</button>
        }
      </div>
    </div>
  );
}
```

---

After pasting, press **Ctrl+S** to save. Then tell me and I'll give you the 2 lines to add to App.jsx to wire it up!