import { useState } from "react";
const DOCS = [{id:"visa",label:"Visa Support Letter"},{id:"roster",label:"Team Roster"},{id:"funding",label:"Funding Request"},{id:"entry",label:"Tournament Entry Form"}];
function printDoc(html,title){const w=window.open("","_blank");w.document.write("<html><head><title>"+title+"</title><style>body{font-family:Arial,sans-serif;padding:40px;max-width:800px;margin:0 auto;}table{width:100%;border-collapse:collapse;}td,th{border:1px solid #ccc;padding:8px;}.hdr{text-align:center;margin-bottom:30px;}</style></head><body>"+html+"</body></html>");w.document.close();w.print();}
function genVisa(d){printDoc("<div class=hdr><h1>VISA SUPPORT LETTER</h1></div><p>This confirms athletes from <b>"+d.club+"</b> travel to <b>"+d.tournament+"</b> in <b>"+d.country+"</b> from "+d.departure+" to "+d.returnDate+". Team: "+d.athletes+" athletes, "+d.coaches+" coaches.</p><p>Head Coach: "+d.headCoach+"</p>","Visa Support Letter");}
function genRoster(d){const rows=d.names.split("\n").map((n,i)=>"<tr><td>"+(i+1)+"</td><td>"+n+"</td><td></td></tr>").join("");printDoc("<div class=hdr><h1>TEAM ROSTER</h1><h2>"+d.club+"</h2></div><table><tr><th>#</th><th>Name</th><th>Weight</th></tr>"+rows+"</table>","Team Roster");}
function genFunding(d){const total=parseInt(d.flightCost||0)+parseInt(d.accomCost||0)+parseInt(d.entryFees||0);printDoc("<div class=hdr><h1>FUNDING REQUEST</h1></div><p>From: "+d.headCoach+", "+d.club+"</p><table><tr><th>Item</th><th>Cost</th></tr><tr><td>Flights</td><td>$"+d.flightCost+"</td></tr><tr><td>Accommodation</td><td>$"+d.accomCost+"</td></tr><tr><td>Entry Fees</td><td>$"+d.entryFees+"</td></tr><tr><td><b>Total</b></td><td><b>$"+total+"</b></td></tr></table><p>"+d.justification+"</p>","Funding Request");}
function genEntry(d){printDoc("<div class=hdr><h1>TOURNAMENT ENTRY FORM</h1><h2>"+d.tournament+"</h2></div><table><tr><th>Club</th><td>"+d.club+"</td></tr><tr><th>Country</th><td>"+d.entryCountry+"</td></tr><tr><th>Coach</th><td>"+d.headCoach+"</td></tr><tr><th>Email</th><td>"+d.email+"</td></tr><tr><th>Athletes</th><td>"+d.athletes+"</td></tr></table>","Tournament Entry Form");}
export default function DocumentGenerator(){
const [t,setT]=useState("visa");
const [d,setD]=useState({club:"",tournament:"",country:"",departure:"",returnDate:"",athletes:"",coaches:"",headCoach:"",email:"",names:"",flightCost:"",accomCost:"",entryFees:"",justification:"",entryCountry:""});
const ch=e=>setD(p=>({...p,[e.target.name]:e.target.value}));
const inp={width:"100%",background:"#1a1a1a",border:"1px solid #333",color:"#fff",padding:"10px",borderRadius:"6px",marginBottom:"12px",boxSizing:"border-box"};
const lbl={display:"block",color:"#ccc",fontSize:"12px",marginBottom:"4px",textTransform:"uppercase"};
const gen=()=>{if(t==="visa")genVisa(d);else if(t==="roster")genRoster(d);else if(t==="funding")genFunding(d);else genEntry(d);};
return(<div style={{minHeight:"100vh",background:"#0a0a0a",padding:"40px 20px"}}><div style={{maxWidth:"700px",margin:"0 auto"}}>
<h1 style={{fontFamily:"Bebas Neue,sans-serif",fontSize:"48px",color:"#f5c518",marginBottom:"8px"}}>DOCUMENT GENERATOR</h1>
<p style={{color:"#888",marginBottom:"32px"}}>Generate official documents for visa applications, funding requests, and tournament entry.</p>
<div style={{display:"flex",gap:"10px",marginBottom:"32px",flexWrap:"wrap"}}>{DOCS.map(x=><button key={x.id} onClick={()=>setT(x.id)} style={{padding:"10px 18px",background:t===x.id?"#f5c518":"#1a1a1a",color:t===x.id?"#000":"#ccc",border:"1px solid "+(t===x.id?"#f5c518":"#333"),borderRadius:"6px",cursor:"pointer"}}>{x.label}</button>)}</div>
<div style={{background:"#111",border:"1px solid #222",borderRadius:"12px",padding:"28px"}}>
<label style={lbl}>Club Name</label><input name="club" value={d.club} onChange={ch} placeholder="e.g. Samoa United Boxing" style={inp}/>
<label style={lbl}>Tournament</label><input name="tournament" value={d.tournament} onChange={ch} placeholder="e.g. Bosnia Open 2026" style={inp}/>
<label style={lbl}>Host Country</label><input name="country" value={d.country} onChange={ch} placeholder="e.g. Bosnia" style={inp}/>
<label style={lbl}>Head Coach</label><input name="headCoach" value={d.headCoach} onChange={ch} placeholder="Full name" style={inp}/>
{(t==="visa"||t==="funding"||t==="entry")&&<><label style={lbl}>Departure Date</label><input name="departure" type="date" value={d.departure} onChange={ch} style={inp}/><label style={lbl}>Return Date</label><input name="returnDate" type="date" value={d.returnDate} onChange={ch} style={inp}/><label style={lbl}>Athletes</label><input name="athletes" value={d.athletes} onChange={ch} placeholder="e.g. 8" style={inp}/><label style={lbl}>Coaches</label><input name="coaches" value={d.coaches} onChange={ch} placeholder="e.g. 2" style={inp}/></>}
{t==="roster"&&<><label style={lbl}>Athlete Names (one per line)</label><textarea name="names" value={d.names} onChange={ch} rows={6} placeholder="John Smith" style={{...inp,resize:"vertical"}}/></>}
{t==="funding"&&<><label style={lbl}>Flight Cost USD</label><input name="flightCost" value={d.flightCost} onChange={ch} placeholder="12000" style={inp}/><label style={lbl}>Accommodation USD</label><input name="accomCost" value={d.accomCost} onChange={ch} placeholder="3500" style={inp}/><label style={lbl}>Entry Fees USD</label><input name="entryFees" value={d.entryFees} onChange={ch} placeholder="800" style={inp}/><label style={lbl}>Justification</label><textarea name="justification" value={d.justification} onChange={ch} rows={4} style={{...inp,resize:"vertical"}}/></>}
{t==="entry"&&<><label style={lbl}>Your Country</label><input name="entryCountry" value={d.entryCountry} onChange={ch} placeholder="Samoa" style={inp}/><label style={lbl}>Email</label><input name="email" value={d.email} onChange={ch} placeholder="coach@example.com" style={inp}/></>}
<button onClick={gen} style={{width:"100%",padding:"14px",background:"#f5c518",color:"#000",border:"none",borderRadius:"8px",fontSize:"16px",fontWeight:"bold",cursor:"pointer",fontFamily:"Bebas Neue,sans-serif",letterSpacing:"2px"}}>GENERATE AND PRINT</button>
</div></div></div>);}
