export const MOCK_ROUTES = [
  {
    id: 1,
    departure_region: 'Pacific Islands',
    departure_country: 'Samoa',
    destination_city: 'Multiple European Cities',
    destination_country: 'Europe (via Istanbul)',
    transit_hubs: ['Istanbul (IST)'],
    airlines: ['Samoa Airways', 'Fiji Airways', 'Turkish Airlines'],
    avg_cost_usd: 1400,
    cost_range_min: 950,
    cost_range_max: 1900,
    flight_hours: '26-34 hours total',
    passport_restrictions: ['Samoan passport: Turkey e-visa required (~$50)', 'Schengen visa required for EU countries'],
    visa_notes: 'Turkish Airlines offers e-visa for Samoan passport holders to transit Turkey ($50 USD). Serbia and Bosnia do NOT require Schengen visa — ideal for Pacific passport holders.',
    tips: 'Turkish Airlines via IST is often best value from the Pacific. For Samoan passports, Belgrade (Serbia) and Sarajevo (Bosnia) are visa-free. Book 3-4 months out for group rates.',
    community_tips: ['We flew Apia → Auckland → Istanbul → Belgrade — smooth connection, great value', 'Turkish Airlines allows 30kg checked — enough for boxing gear'],
  },
  {
    id: 2,
    departure_region: 'Pacific Islands',
    departure_country: 'Samoa',
    destination_city: 'Multiple European Cities',
    destination_country: 'Europe (via Dubai)',
    transit_hubs: ['Dubai (DXB)'],
    airlines: ['Samoa Airways', 'Fiji Airways', 'Emirates'],
    avg_cost_usd: 1550,
    cost_range_min: 1100,
    cost_range_max: 2100,
    flight_hours: '26-32 hours total',
    passport_restrictions: ['Samoan passport: check UAE transit visa — contact Emirates', 'Schengen visa required for EU countries'],
    visa_notes: 'Emirates may require transit visa for Samoan passport — contact airline directly before booking. Good luggage allowance for sports equipment. Schengen visa required for EU entry.',
    tips: 'Emirates via Dubai is reliable and has excellent baggage allowance (30kg economy). Check UAE transit visa early. Great in-flight service for long hauls.',
    community_tips: [],
  },
  {
    id: 3,
    departure_region: 'Pacific Islands',
    departure_country: 'Samoa',
    destination_city: 'Multiple European Cities',
    destination_country: 'Europe (via Singapore)',
    transit_hubs: ['Singapore (SIN)'],
    airlines: ['Samoa Airways', 'Singapore Airlines', 'Lufthansa'],
    avg_cost_usd: 1650,
    cost_range_min: 1200,
    cost_range_max: 2200,
    flight_hours: '24-30 hours total',
    passport_restrictions: ['Samoan passport: visa-free Singapore transit under 96hrs', 'Schengen visa required for EU countries'],
    visa_notes: 'Singapore Airlines via SIN is the most reliable Pacific-Europe routing. Singapore transit is visa-free for Samoan passports under 96 hours. Schengen visa still required for EU entry.',
    tips: 'Singapore Airlines is the gold standard for Pacific-Europe. Most reliable, best service. Book 3-4 months out. SIN airport excellent for long layovers.',
    community_tips: ['Singapore Airlines was excellent — on-time, great baggage handling for our equipment'],
  },
  {
    id: 4,
    departure_region: 'Pacific Islands',
    departure_country: 'Samoa',
    destination_city: 'Los Angeles',
    destination_country: 'United States (via Fiji)',
    transit_hubs: ['Nadi (NAN)'],
    airlines: ['Samoa Airways', 'Fiji Airways'],
    avg_cost_usd: 1100,
    cost_range_min: 750,
    cost_range_max: 1600,
    flight_hours: '14-18 hours total',
    passport_restrictions: ['Samoan passport: US visa required (B1/B2 or P1 athlete)', 'US visa takes 8-12 weeks — apply early'],
    visa_notes: 'Samoan passport holders need a US visa for USA travel. Apply at US Embassy in Apia — minimum 12 weeks processing time. P1 athlete visa required for competing athletes.',
    tips: 'Fiji Airways via NAN is the standard Pacific-USA route. Great for groups. Apply for US visas as early as possible — this is the biggest risk for USA tournaments.',
    community_tips: ['Start US visa process 4 months before departure', 'Fiji Airways excellent group rates for 10+ travellers'],
  },
  {
    id: 5,
    departure_region: 'Pacific Islands',
    departure_country: 'Samoa',
    destination_city: 'Los Angeles',
    destination_country: 'United States (via Auckland)',
    transit_hubs: ['Auckland (AKL)'],
    airlines: ['Samoa Airways', 'Air New Zealand'],
    avg_cost_usd: 1200,
    cost_range_min: 850,
    cost_range_max: 1750,
    flight_hours: '16-20 hours total',
    passport_restrictions: ['Samoan passport: NZeTA required for NZ transit ($17 NZD online)', 'US visa required'],
    visa_notes: 'NZeTA required for Samoa passport to transit New Zealand — apply online at nzeta.immigration.govt.nz ($17 NZD, takes 72hrs). US visa still required for USA entry.',
    tips: 'Air New Zealand via AKL offers excellent service. NZeTA is cheap and quick. Good option if Fiji routing is full or pricier.',
    community_tips: [],
  },
  {
    id: 6,
    departure_region: 'Pacific Islands',
    departure_country: 'Samoa',
    destination_city: 'Multiple European Cities',
    destination_country: 'Europe (via Doha)',
    transit_hubs: ['Doha (DOH)'],
    airlines: ['Samoa Airways', 'Fiji Airways', 'Qatar Airways'],
    avg_cost_usd: 1500,
    cost_range_min: 1050,
    cost_range_max: 2000,
    flight_hours: '26-32 hours total',
    passport_restrictions: ['Samoan passport: Qatar transit visa-free under 24hrs', 'Schengen visa required for EU countries'],
    visa_notes: 'Qatar Airways offers transit visa-free for Samoan passports under 24 hours in Doha. Premium service, excellent baggage allowance. Schengen visa required for EU entry.',
    tips: 'Qatar Airways via DOH is premium at mid-range price. Business class upgrades worthwhile for long haul. Doha airport excellent for layovers.',
    community_tips: [],
  },
  // Europe departures
  {
    id: 7,
    departure_region: 'Europe',
    departure_country: 'Ireland',
    destination_city: 'Belgrade',
    destination_country: 'Serbia',
    transit_hubs: ['Vienna (VIE)', 'Frankfurt (FRA)'],
    airlines: ['Ryanair', 'Air Serbia', 'Lufthansa', 'Austrian Airlines'],
    avg_cost_usd: 180,
    cost_range_min: 80,
    cost_range_max: 350,
    flight_hours: '4-6 hours with connection',
    passport_restrictions: [],
    visa_notes: 'EU/EEA and UK passport holders: no visa required for Serbia. Serbia is not in Schengen — no issues for most EU passports.',
    tips: 'Ryanair via Vienna or Lufthansa/Austrian via Frankfurt are the best options from Ireland. Air Serbia flies direct from some European hubs. Book 6-8 weeks out.',
    community_tips: ['Ryanair to Vienna then Austrian to Belgrade — cheapest option usually under €100 return'],
  },
  {
    id: 8,
    departure_region: 'Europe',
    departure_country: 'United Kingdom',
    destination_city: 'Sarajevo',
    destination_country: 'Bosnia & Herzegovina',
    transit_hubs: ['Vienna (VIE)', 'Zagreb (ZAG)'],
    airlines: ['Ryanair', 'Wizz Air', 'Austrian Airlines', 'Croatia Airlines'],
    avg_cost_usd: 220,
    cost_range_min: 100,
    cost_range_max: 400,
    flight_hours: '4-7 hours with connection',
    passport_restrictions: [],
    visa_notes: 'UK passport holders: no visa required for Bosnia & Herzegovina. Bosnia is not in Schengen — straightforward entry.',
    tips: 'No direct UK-Sarajevo flights. Best routing: Ryanair to Vienna or Zagreb, then connect. Austrian Airlines via VIE is most reliable. Book at least 2 months ahead.',
    community_tips: [],
  },
]
