export const MOCK_TOURNAMENTS = [
  {
    id: 1,
    name: "Sarajevo Open Boxing Championship",
    sport: "Boxing",
    country: "Bosnia & Herzegovina",
    city: "Sarajevo",
    flag: "🇧🇦",
    start_date: "2025-03-14",
    end_date: "2025-03-18",
    age_groups: ["Youth (17-18)", "Elite (19-40)"],
    entry_fee: "€180 per boxer",
    visa_notes: "Schengen visa NOT required for most EU passport holders. UK nationals: visa-free for 90 days. US nationals: visa-free. Check requirements 6 weeks in advance.",
    level: "International",
    total_teams: 24,
    description: "One of the Balkans' most celebrated amateur boxing tournaments, held in the historic Zetra Olympic Hall. Attracts elite clubs from across Europe.",
    reviews: [
      {
        id: 101,
        team_name: "Dublin BC",
        country: "Ireland",
        flag: "🇮🇪",
        coach: "Paddy Doyle",
        accommodation: "Hotel Central Sarajevo — €45/night, 10 min walk to venue",
        total_cost_per_person: "€620",
        flight_route: "Dublin → Vienna (Ryanair) → Sarajevo (Austrian Air) — approx €160 return",
        tips: "Book flights 3 months out. The Baščaršija area has great local food for under €10/meal. Weigh-in is strict — bring your own scales. Venue has no café so pack snacks.",
        rating: 5,
        date_attended: "March 2024",
      },
      {
        id: 102,
        team_name: "Glasgow Caledonian ABC",
        country: "Scotland",
        flag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
        coach: "Steven Reid",
        accommodation: "Hostel City Center — €28/night per person, basic but clean",
        total_cost_per_person: "€490",
        flight_route: "Glasgow → London Heathrow → Sarajevo — approx €195 return",
        tips: "Fantastic atmosphere, well-organised draws. Referees are top level. Sarajevo taxis are cash only. The local sponsors provide free transport from airport if you register on time.",
        rating: 4,
        date_attended: "March 2024",
      },
    ],
  },
  {
    id: 2,
    name: "Sofia International Boxing Cup",
    sport: "Boxing",
    country: "Bulgaria",
    city: "Sofia",
    flag: "🇧🇬",
    start_date: "2025-05-08",
    end_date: "2025-05-12",
    age_groups: ["Youth (17-18)", "Elite (19-40)"],
    entry_fee: "€150 per boxer",
    visa_notes: "Bulgaria is EU but NOT yet Schengen. EU/EEA nationals: ID card sufficient. UK nationals: passport required, visa-free 90 days. US nationals: visa-free.",
    level: "International",
    total_teams: 18,
    description: "Annual cup hosted by the Bulgarian Boxing Federation at the National Sports Palace. Known for competitive Senior and Junior categories.",
    reviews: [
      {
        id: 201,
        team_name: "Kronk Gym UK",
        country: "England",
        flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
        coach: "Marcus Bell",
        accommodation: "Radisson Blu — €90/night, close to the National Palace of Culture",
        total_cost_per_person: "€780",
        flight_route: "London Heathrow → Sofia (British Airways) — approx €210 return",
        tips: "Excellent organisation, English-speaking officials. Metro is cheap and runs to the venue. Bring euros — many places don't take card. Great steakhouses near the venue for team dinners.",
        rating: 5,
        date_attended: "May 2024",
      },
    ],
  },
  {
    id: 3,
    name: "Belgrade Golden Gloves",
    sport: "Boxing",
    country: "Serbia",
    city: "Belgrade",
    flag: "🇷🇸",
    start_date: "2025-07-22",
    end_date: "2025-07-27",
    age_groups: ["Elite (19-40)"],
    entry_fee: "€200 per boxer",
    visa_notes: "Serbia is NOT in the EU or Schengen. EU nationals: visa-free 90 days. UK nationals: visa-free 90 days. US nationals: visa-free 90 days. No visa required for most Western countries.",
    level: "Elite International",
    total_teams: 32,
    description: "The premier summer boxing tournament in the Western Balkans. Held at Hala Pionir arena. Features 32 national teams and draws significant media coverage.",
    reviews: [
      {
        id: 301,
        team_name: "Berlin Boxring eV",
        country: "Germany",
        flag: "🇩🇪",
        coach: "Klaus Müller",
        accommodation: "Mama Shelter Belgrade — €65/night, excellent location",
        total_cost_per_person: "€540",
        flight_route: "Berlin Brandenburg → Belgrade (Air Serbia) — approx €120 return",
        tips: "Air Serbia flies direct from many European hubs. Serbian dinars are needed — exchange at airport. Massive event, fantastic crowds. Draw ceremony is formal — bring club tracksuits. July heat can affect weight management.",
        rating: 5,
        date_attended: "July 2024",
      },
      {
        id: 302,
        team_name: "Lyon Boxe Club",
        country: "France",
        flag: "🇫🇷",
        coach: "Antoine Beaumont",
        accommodation: "Hotel Metropol — €55/night, city center, 15 min to arena",
        total_cost_per_person: "€610",
        flight_route: "Lyon → Belgrade via Vienna (Austrian) — approx €180 return",
        tips: "One of the best tournaments in Europe. Officials are AIBA certified. Belgrade nightlife is legendary — manage your boxers carefully the night before bouts! Street food on Skadarlija is incredible.",
        rating: 4,
        date_attended: "July 2024",
      },
    ],
  },
  {
    id: 4,
    name: "Zagreb Croatia Boxing Classic",
    sport: "Boxing",
    country: "Croatia",
    city: "Zagreb",
    flag: "🇭🇷",
    start_date: "2025-09-19",
    end_date: "2025-09-22",
    age_groups: ["Junior (15-16)"],
    entry_fee: "€130 per boxer",
    visa_notes: "Croatia IS in Schengen since 2023. Standard Schengen rules apply. EU nationals: ID card sufficient. UK nationals: passport required, visa-free 90 days. US nationals: visa-free.",
    level: "Regional",
    total_teams: 14,
    description: "Youth-focused tournament run by the Croatian Boxing Association. Great first international for younger squads — well-supported, safe environment.",
    reviews: [
      {
        id: 401,
        team_name: "Swansea ABC",
        country: "Wales",
        flag: "🏴󠁧󠁢󠁷󠁬󠁳󠁿",
        coach: "Gareth Evans",
        accommodation: "Hostel Bureau Zagreb — €22/night, excellent and central",
        total_cost_per_person: "€390",
        flight_route: "Bristol → Zagreb (Wizz Air) — approx €85 return",
        tips: "Perfect introductory international for youth teams. Zagreb is stunning and very safe. Use Wizz Air — ridiculously cheap. The tournament director speaks perfect English. Bring your own wraps, they don't provide any.",
        rating: 5,
        date_attended: "September 2024",
      },
    ],
  },
  {
    id: 5,
    name: "Warsaw Winter Boxing Cup",
    sport: "Boxing",
    country: "Poland",
    city: "Warsaw",
    flag: "🇵🇱",
    start_date: "2025-11-07",
    end_date: "2025-11-10",
    age_groups: ["Elite (19-40)"],
    entry_fee: "€160 per boxer",
    visa_notes: "Poland is in Schengen. EU nationals: ID card sufficient. UK nationals: visa-free 90 days. US nationals: visa-free. PLN currency accepted everywhere; euros less common.",
    level: "International",
    total_teams: 20,
    description: "Late-season European circuit fixture held at Legia Warsaw Sports Centre. Draws strong entries from Poland, Ukraine, Czech Republic, and UK clubs.",
    reviews: [
      {
        id: 501,
        team_name: "Northside BC Dublin",
        country: "Ireland",
        flag: "🇮🇪",
        coach: "Jim Connolly",
        accommodation: "ibis Budget Warsaw Centre — €38/night, functional and affordable",
        total_cost_per_person: "€510",
        flight_route: "Dublin → Warsaw (Ryanair) — approx €90 return, direct",
        tips: "November is cold — pack thermal base layers for weigh-in mornings. Warsaw is brilliant value. Ryanair flies direct from Dublin which is a game changer. Polish food is hearty and perfect for fighters — try żurek. Officials run a tight schedule, no delays.",
        rating: 4,
        date_attended: "November 2024",
      },
    ],
  },
]

export const SPORTS = ["All Sports", "Boxing", "Wrestling", "Judo", "Taekwondo", "Kickboxing", "MMA"]
export const AGE_GROUPS = ["All Ages", "Junior (15-16)", "Youth (17-18)", "Elite (19-40)", "Masters (40+)"]
export const MONTHS = [
  "All Months", "January", "February", "March", "April", "May", "June",
  "July", "August", "September", "October", "November", "December",
]
